steps:
  - name: "gcr.io/cloud-builders/gcloud"
    entrypoint: "bash"
    args:
      [
        "-c",
        "gcloud app deploy app.yaml",
      ]
timeout: "1600s"
options:
 logging: CLOUD_LOGGING_ONLY

